### ISSUE TITLE
在jdk8环境下，搭建libreoffice+minio环境下的文件预览报错

### ISSUE THREAD

**Issue by fmonkeyaksd** [wb04307201/file-preview-spring-boot-starter#1]
配置文件为：
file:
  storage:
    minIO: # MinIO
      - enable-storage: true  # 启用存储
        access-key: l3yY6ZmQ5fAblTFv0wOp
        secret-key: eeZdwrtCMpDWyCZG128dnYAxCAOyP8ioXaU2RiXp
        end-point: http://192.168.43.152:9002
        bucket-name: testfilestorage
        base-path: temp/ # 基础路径
        alias: minio-1 # 别名
    file-storage-record: org.example.demo1.H2FileStroageRecordImpl
  preview:
    officeConverter: lool
    file-preview-record: org.example.demo1.H2FilePriviewRecordImpl
    file-storage: org.example.demo1.MinIOFileStorageImpl
    libreoffice:
      domain: http://192.168.43.152:9980  #libreoffice online服务所在地址
      storage: /opt/lool

文件在执行save()方法后，已成功插入到minio中，但是/opt/lool目录下没有任何数据，预览时报如下错误：
Servlet.service() for servlet [previewServlet] in context with path [] threw exception

cn.wubo.file.preview.exception.PageRuntimeException: cn.wubo.file.preview.page.impl.LoolPage.<init>(java.lang.String, java.lang.String, java.lang.String, cn.wubo.file.preview.core.FilePreviewInfo, cn.wubo.file.preview.core.FilePreviewService, cn.wubo.file.preview.config.FilePreviewProperties, javax.servlet.http.HttpServletResponse)
	at cn.wubo.file.preview.page.PageFactory.create(PageFactory.java:40) ~[file-preview-spring-boot-starter-1.1.10.jar:na]
	at cn.wubo.file.preview.servlet.PreviewServlet.doGet(PreviewServlet.java:34) ~[file-preview-spring-boot-starter-1.1.10.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:670) ~[tomcat-embed-core-9.0.68.jar:4.0.FR]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[tomcat-embed-core-9.0.68.jar:4.0.FR]

**Comment by wb04307201** [comment]
上次发布的版本1.1.15使用了错误的代码分支，到时jdk版本不匹配，请更换成1.1.16版本
