### ISSUE TITLE
jdk8环境下1.1.8版本的pdf文件在低版本chrome浏览器（版本号：75.0.3770.100）和Edge（版本90.0.818.66）预览失败，请问怎样解决？

### ISSUE THREAD

**Issue by fmonkeyaksd** [wb04307201/file-preview-spring-boot-starter#2]

**Comment by wb04307201** [comment]
预览pdf使用了https://github.com/mozilla/pdf.js这个项目，
![image](https://github.com/wb04307201/file-preview-spring-boot-starter/assets/35208417/3795a65f-1910-41e6-aa85-7e6d9b3f7df9)
按照文档描述使用legacy build至少也需要chrome 92+以上版本，
可以尝试参照文档中的这部分，
![image](https://github.com/wb04307201/file-preview-spring-boot-starter/assets/35208417/56f2fbd2-76b2-49e2-9715-c0314e257fd7)
自定义渲染方式处理，
尝试直接将pdf弹回到浏览器看看是否能直接显示，
或者试试使用其他兼容耕地版本浏览器的组件协助显示

**Comment by fmonkeyaksd** [comment]
1.1.8版本的file-preview-spring-boot-starter怎样自定义渲染方式呢？
